'use strict';
// Default unit-key catalogue of the FP7 dynamic Modbus program (array `keys`).
// Same content as unit_keys.csv of FP7 Modbus Configurator. [code, key, unit, quantity, group, kind, decimals]
// kind: C = counter (cumulative), I = instantaneous
module.exports = [
    [1, "kWh", "kWh", "Điện năng tác dụng tiêu thụ (nhận)", "Điện", "C", 1],
    [2, "kW", "kW", "Công suất tác dụng tổng", "Điện", "I", 2],
    [3, "I1", "A", "Dòng điện pha 1 (L1)", "Điện", "I", 2],
    [4, "I2", "A", "Dòng điện pha 2 (L2)", "Điện", "I", 2],
    [5, "I3", "A", "Dòng điện pha 3 (L3)", "Điện", "I", 2],
    [6, "I", "A", "Dòng điện trung bình 3 pha", "Điện", "I", 2],
    [7, "U1", "V", "Điện áp pha L1-N", "Điện", "I", 1],
    [8, "U2", "V", "Điện áp pha L2-N", "Điện", "I", 1],
    [9, "U3", "V", "Điện áp pha L3-N", "Điện", "I", 1],
    [10, "U", "V", "Điện áp pha trung bình", "Điện", "I", 1],
    [11, "PF", "", "Hệ số công suất tổng (cosφ)", "Điện", "I", 3],
    [12, "Hz", "Hz", "Tần số", "Điện", "I", 2],
    [13, "U12", "V", "Điện áp dây L1-L2", "Điện", "I", 1],
    [14, "U23", "V", "Điện áp dây L2-L3", "Điện", "I", 1],
    [15, "U31", "V", "Điện áp dây L3-L1", "Điện", "I", 1],
    [16, "ULL", "V", "Điện áp dây trung bình", "Điện", "I", 1],
    [17, "In", "A", "Dòng điện dây trung tính", "Điện", "I", 2],
    [18, "P1", "kW", "Công suất tác dụng pha 1", "Điện", "I", 2],
    [19, "P2", "kW", "Công suất tác dụng pha 2", "Điện", "I", 2],
    [20, "P3", "kW", "Công suất tác dụng pha 3", "Điện", "I", 2],
    [21, "kvar", "kvar", "Công suất phản kháng tổng", "Điện", "I", 2],
    [22, "kVA", "kVA", "Công suất biểu kiến tổng", "Điện", "I", 2],
    [23, "kvarh", "kvarh", "Điện năng phản kháng", "Điện", "C", 1],
    [24, "kVAh", "kVAh", "Điện năng biểu kiến", "Điện", "C", 1],
    [25, "kWh_EXP", "kWh", "Điện năng tác dụng phát ngược (xuất, VD: điện mặt trời)", "Điện", "C", 1],
    [26, "MWh", "MWh", "Điện năng tác dụng (công tơ lớn)", "Điện", "C", 3],
    [27, "kW_DMD", "kW", "Công suất cực đại (Max demand)", "Điện", "I", 2],
    [28, "PF1", "", "Hệ số công suất pha 1", "Điện", "I", 3],
    [29, "PF2", "", "Hệ số công suất pha 2", "Điện", "I", 3],
    [30, "PF3", "", "Hệ số công suất pha 3", "Điện", "I", 3],
    [31, "THD_U", "%", "Méo hài tổng điện áp", "Điện", "I", 1],
    [32, "THD_I", "%", "Méo hài tổng dòng điện", "Điện", "I", 1],
    [33, "kWh_T1", "kWh", "Điện năng giờ bình thường (biểu giá 1)", "Điện", "C", 1],
    [34, "kWh_T2", "kWh", "Điện năng giờ cao điểm (biểu giá 2)", "Điện", "C", 1],
    [35, "kWh_T3", "kWh", "Điện năng giờ thấp điểm (biểu giá 3)", "Điện", "C", 1],
    [100, "W_m3", "m3", "Nước - tổng lưu lượng tích luỹ", "Nước", "C", 1],
    [101, "W_m3h", "m3/h", "Nước - lưu lượng tức thời", "Nước", "I", 2],
    [102, "W_L", "L", "Nước - tổng tích luỹ (lít)", "Nước", "C", 0],
    [103, "W_Lmin", "L/min", "Nước - lưu lượng tức thời (lít/phút)", "Nước", "I", 1],
    [104, "W_bar", "bar", "Nước - áp suất đường ống", "Nước", "I", 2],
    [105, "W_level", "m", "Nước - mực nước bể", "Nước", "I", 2],
    [106, "W_levelp", "%", "Nước - mực nước bể (%)", "Nước", "I", 1],
    [107, "W_temp", "°C", "Nước - nhiệt độ (nước cấp, nước làm mát)", "Nước", "I", 1],
    [108, "W_pH", "pH", "Nước - độ pH (nước thải)", "Nước", "I", 2],
    [150, "A_Nm3", "Nm3", "Khí nén - tổng lưu lượng tích luỹ", "Khí nén", "C", 1],
    [151, "A_Nm3h", "Nm3/h", "Khí nén - lưu lượng tức thời", "Khí nén", "I", 1],
    [152, "A_Nm3min", "Nm3/min", "Khí nén - lưu lượng tức thời (m3/phút)", "Khí nén", "I", 2],
    [153, "A_bar", "bar", "Khí nén - áp suất", "Khí nén", "I", 2],
    [154, "A_temp", "°C", "Khí nén - nhiệt độ", "Khí nén", "I", 1],
    [155, "A_dew", "°Ctd", "Khí nén - điểm sương áp suất", "Khí nén", "I", 1],
    [156, "A_m3", "m3", "Khí nén - tổng tích luỹ (m3 thực)", "Khí nén", "C", 1],
    [200, "G_Nm3", "Nm3", "Gas - tổng lưu lượng tích luỹ (khí thiên nhiên, CNG)", "Gas", "C", 1],
    [201, "G_Nm3h", "Nm3/h", "Gas - lưu lượng tức thời", "Gas", "I", 2],
    [202, "G_m3", "m3", "Gas - tổng tích luỹ (m3 thực, chưa quy chuẩn)", "Gas", "C", 1],
    [203, "G_kg", "kg", "Gas LPG - tổng khối lượng tích luỹ", "Gas", "C", 1],
    [204, "G_kgh", "kg/h", "Gas LPG - lưu lượng khối lượng tức thời", "Gas", "I", 2],
    [205, "G_kPa", "kPa", "Gas - áp suất", "Gas", "I", 2],
    [206, "G_temp", "°C", "Gas - nhiệt độ", "Gas", "I", 1],
    [207, "G_level", "%", "Gas LPG - mức bồn chứa", "Gas", "I", 1],
    [208, "G_mbar", "mbar", "Gas - áp suất thấp (sau van giảm áp)", "Gas", "I", 1],
    [250, "S_t", "t", "Hơi - tổng khối lượng tích luỹ (tấn)", "Hơi/Nhiệt", "C", 2],
    [251, "S_th", "t/h", "Hơi - lưu lượng tức thời", "Hơi/Nhiệt", "I", 3],
    [252, "S_bar", "bar", "Hơi - áp suất", "Hơi/Nhiệt", "I", 2],
    [253, "S_temp", "°C", "Hơi - nhiệt độ", "Hơi/Nhiệt", "I", 1],
    [254, "H_kWh", "kWh", "Nhiệt năng (đồng hồ BTU / nước nóng-lạnh)", "Hơi/Nhiệt", "C", 1],
    [255, "H_kW", "kW", "Công suất nhiệt", "Hơi/Nhiệt", "I", 2],
    [256, "H_GJ", "GJ", "Nhiệt năng (GJ)", "Hơi/Nhiệt", "C", 3],
    [257, "H_RT", "RT", "Công suất lạnh (Refrigeration Ton - chiller)", "Hơi/Nhiệt", "I", 1],
    [300, "TEMP", "°C", "Nhiệt độ", "Môi trường", "I", 1],
    [301, "RH", "%RH", "Độ ẩm tương đối", "Môi trường", "I", 1],
    [302, "P_bar", "bar", "Áp suất", "Môi trường", "I", 2],
    [303, "P_kPa", "kPa", "Áp suất (kPa)", "Môi trường", "I", 1],
    [304, "P_MPa", "MPa", "Áp suất (MPa)", "Môi trường", "I", 3],
    [305, "P_Pa", "Pa", "Chênh áp (phòng sạch, lọc)", "Môi trường", "I", 1],
    [306, "DEW", "°Ctd", "Điểm sương", "Môi trường", "I", 1],
    [307, "CO2", "ppm", "Nồng độ CO2", "Môi trường", "I", 0],
    [308, "PM25", "µg/m3", "Bụi mịn PM2.5", "Môi trường", "I", 0],
    [309, "LUX", "lux", "Độ rọi ánh sáng", "Môi trường", "I", 0],
    [310, "T_OUT", "°C", "Nhiệt độ ngoài trời", "Môi trường", "I", 1],
    [311, "RH_OUT", "%RH", "Độ ẩm ngoài trời", "Môi trường", "I", 1],
    [900, "RUN_H", "h", "Số giờ chạy tích luỹ", "Chung", "C", 1],
    [901, "COUNT", "pcs", "Bộ đếm (sản lượng, số lần)", "Chung", "C", 0],
    [902, "PCT", "%", "Phần trăm (độ mở van, tải…)", "Chung", "I", 1],
    [903, "RPM", "rpm", "Tốc độ quay", "Chung", "I", 0],
    [904, "STATE", "", "Trạng thái (0/1, mã lỗi)", "Chung", "I", 0],
    [905, "kg", "kg", "Khối lượng", "Chung", "C", 2],
    [906, "t", "t", "Khối lượng (tấn)", "Chung", "C", 3],
    [907, "m", "m", "Chiều dài / mức", "Chung", "I", 2]
];
